### ISSUE TITLE
Можно интерфейс сделать чуть дружелюбнее, щас не очень понятно в какой последовательности включать.

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleTelegramProvider#3]
Можно прямо на форму добавить по шагам, короткую инструкцию встроенную в форму

_Шаг первый_:
Получите "App api_id" и "App api_hash" по ссылке и введите в поля ниже
**поле api_id  как сейчс**
**поле api_hash  как сейчс**

_Шаг второй_:
Нажмите кнопку сохранить и включите модуль.

_Шаг третий_: 
Впишите номер телефона от учетной записи Telegram, и введите код активации полученный в приложении:
**Кнопка добавить как сейчас** 
**Таблица линий как сейчас**

_Шаг четвертый_:
Дождитесь пока модуль авторизуется в сети Telegram и вручную настройте провайдера, входящие и исходящие маршруты. В общих настройках включите кодек OPUS.

Все это вписать в файл с русским языком, остальные сформируются автоматически через weblate. 
И будем отгружать модуль. Я думаю так намного меньше будет вопросов.

**Comment by boffart** [comment]
<img width="1135" alt="MikoPBX_Провайдер_Telegram" src="https://user-images.githubusercontent.com/5922739/154053084-ec341909-6195-45d8-8edb-1c6856d6c883.png">
поправил.
