### ISSUE TITLE
Дополнить инструкцию wiki о настройках безопасности в самом телеграм

### ISSUE THREAD

**Issue by jorikfon** [mikopbx/ModuleTelegramProvider#4]
На той учетке которую настраиваем надо разрешить звонки ото всех, иначе будет отбивать вызовы, не поймут в чем дело. По умолчанию там только от контактов разрешен прием вызова.

Еще не знаю про опцию peer-to-peer в какое положение ее лучшет ставить, там написано что влияет на качество звонков.

**Comment by jorikfon** [comment]
![IMG_7F0255F3D398-1](https://user-images.githubusercontent.com/5922918/151774224-83a507e3-65c1-4191-b366-167ba7635831.jpeg)

**Comment by boffart** [comment]
Дополнил инструкции
https://wiki.mikopbx.com/module-telegram-provider#poluchenie_app_api_id_i_app_api_hash

по поводу P2P пока ничего не писал. Не понятно что с этим делать.
